import React, { useState, useEffect } from "react";
import { apiService } from "../../../manageApi/utils/custom.apiservice";
import {
  Table,
  Tag,
  Space,
  Card,
  Typography,
  Row,
  Col,
  Statistic,
  Button,
  Modal,
  Input,
  Select,
  Avatar,
  Divider,
  message
} from "antd";

import {
  UserOutlined,
  PhoneOutlined,
  MailOutlined,
  SearchOutlined,
  EyeOutlined,
  MessageOutlined,
  PropertySafetyOutlined,
  CompassOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  TeamOutlined   // ← agent section ke liye
} from "@ant-design/icons";

const { Title, Text } = Typography;
const { Option } = Select;

const LeadManagement = () => {
  const [leads, setLeads] = useState([]);
  const [loading, setLoading] = useState(false);
  
  const [searchText, setSearchText] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");

  const [viewModal, setViewModal] = useState(false);
  const [selectedLead, setSelectedLead] = useState(null);

  // ================= FETCH LEADS =================
  const fetchLeads = async () => {
    try {
      setLoading(true);
      const res = await apiService.get("/agent/lead/get-all-leads");
      const list = Array.isArray(res?.data)
        ? res.data
        : res?.data?.data || [];
         
      setLeads(list);
    } catch (error) {
      message.error("Failed to fetch leads.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLeads();
  }, []);

  // ================= STATUS TAG =================
  const getStatusTag = (status) => {
    const colors = {
      lead: "#03A4F4",
      visit: "#5C039B",
      deal: "#D67A56",
      booking: "#020202",
      closed: "#64EF0A",
      lost: "#EF4444"
    };
    return (
      <Tag style={{ backgroundColor: colors[status] || "#6B7280", color: "#fff" }}>
        {status?.toUpperCase() || "UNKNOWN"}
      </Tag>
    );
  };

  // ================= TABLE DATA & FILTERING =================
  const tableData = leads
    .map((l) => ({
      ...l,
      key: l._id,
      leadName: `${l?.name?.first_name || ""} ${l?.name?.last_name || ""}`,
      email: l?.email,
      phone: l?.phone_number,
      agentName: `${l?.agent?.first_name || ""} ${l?.agent?.last_name || ""}`,
      agentEmail: l?.agent?.email || "",
      agentPhone: l?.agent?.phone_number || l?.agent?.phone || "",
      createdAtFormatted: new Date(l.createdAt).toLocaleDateString(),
    }))
    .filter((l) => {
      const matchSearch =
        l.leadName.toLowerCase().includes(searchText.toLowerCase()) ||
        (l.email && l.email.toLowerCase().includes(searchText.toLowerCase()));
      const matchStatus = statusFilter === "all" || l.status === statusFilter;
      return matchSearch && matchStatus;
    });

  // ================= MAIN TABLE COLUMNS =================
  const columns = [
    {
      title: "Lead Details",
      render: (_, r) => (
        <Space>
          <Avatar icon={<UserOutlined />} style={{ backgroundColor: "#03A4F4" }} />
          <div>
            <Text strong style={{ color: "#020202" }}>{r.leadName}</Text>
            <br />
            <Text type="secondary" style={{ fontSize: 12 }}>{r.email}</Text>
          </div>
        </Space>
      ),
    },
    {
      title: "Agent",
      dataIndex: "agentName",
      render: (text) => <Tag style={{ backgroundColor: "#5C039B", color: "#fff" }}>{text}</Tag>
    },
    {
      title: "Property Type",
      render: (record) => (
        <Text strong style={{ color: "#020202" }}>
          <CompassOutlined className="mr-1" style={{ color: "#5C039B" }} /> {record.property_type || "-"}
        </Text>
      ),
    },
    {
      title: "Status",
      dataIndex: "status",
      render: (status) => getStatusTag(status),
    },
    {
      title: "Date",
      dataIndex: "createdAtFormatted",
    },
    {
      title: "Action",
      render: (_, record) => (
        <Button
          type="primary"
          ghost
          icon={<EyeOutlined />}
          style={{ borderColor: "#5C039B", color: "#5C039B" }}
          onClick={() => {
            setSelectedLead(record);
            setViewModal(true);
          }}
        >
          View Lead
        </Button>
      ),
    },
  ];

  return (
    <div className="p-6" style={{ backgroundColor: "#F2EBF7", minHeight: "100vh" }}>
      {/* HEADER */}
      <div className="mb-6">
        <Title level={2} style={{ margin: 0, color: "#5C039B" }}>Lead Monitoring</Title>
        <Text type="secondary" style={{ color: "#547593" }}>
          Monitor all leads generated by agents, track their statuses, and view complete details.
        </Text>
      </div>

      {/* PIPELINE STATS */}
      <Row gutter={[16, 16]} className="mb-8">
        <Col xs={24} sm={6}>
          <Card bordered={false} className="shadow-sm rounded-xl">
            <Statistic
              title="Total Leads"
              value={leads.length}
              prefix={<MessageOutlined style={{ color: "#03A4F4" }} />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={6}>
          <Card bordered={false} className="shadow-sm rounded-xl">
            <Statistic
              title="Site Visits"
              value={leads.filter((l) => l.status === "visit").length}
              prefix={<CompassOutlined style={{ color: "#5C039B" }} />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={6}>
          <Card bordered={false} className="shadow-sm rounded-xl">
            <Statistic
              title="Active Deals"
              value={leads.filter((l) => l.status === "deal").length}
              prefix={<ClockCircleOutlined style={{ color: "#D67A56" }} />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={6}>
          <Card bordered={false} className="shadow-sm rounded-xl">
            <Statistic
              title="Successfully Closed"
              value={leads.filter((l) => l.status === "closed").length}
              prefix={<CheckCircleOutlined style={{ color: "#64EF0A" }} />}
            />
          </Card>
        </Col>
      </Row>

      {/* LEAD TABLE WITH FILTERS */}
      <Card bordered={false} className="shadow-md rounded-xl">
        <div className="mb-4 flex gap-4 flex-wrap">
          <Input
            prefix={<SearchOutlined style={{ color: "#547593" }} />}
            placeholder="Search by Lead Name or Email..."
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
            style={{ width: 300 }}
            size="large"
          />
          <Select
            value={statusFilter}
            onChange={(val) => setStatusFilter(val)}
            style={{ width: 180 }}
            size="large"
          >
            <Option value="all">All Statuses</Option>
            <Option value="lead">New Leads</Option>
            <Option value="visit">Site Visits</Option>
            <Option value="deal">In Deal</Option>
            <Option value="booking">Booked</Option>
            <Option value="closed">Closed</Option>
            <Option value="lost">Lost</Option>
          </Select>
        </div>

        <Table
          columns={columns}
          dataSource={tableData}
          loading={loading}
          pagination={{ pageSize: 10 }}
        />
      </Card>

      {/* MODAL: VIEW FULL LEAD DETAILS */}
      <Modal
        title={
          <Space>
            <UserOutlined style={{ color: "#5C039B" }} />
            <span style={{ color: "#5C039B" }}>Complete Lead Details</span>
          </Space>
        }
        open={viewModal}
        onCancel={() => setViewModal(false)}
        footer={[
          <Button key="close" style={{ backgroundColor: "#5C039B", borderColor: "#5C039B" }} onClick={() => setViewModal(false)}>
            Close
          </Button>,
        ]}
        width={700}
      >
        {selectedLead && (
          <div className="mt-4">

            {/* ── Lead Name + Status ── */}
            <Row gutter={[16, 16]}>
              <Col span={12}>
                <Text type="secondary" style={{ color: "#547593" }}>Lead Name</Text>
                <br />
                <Text strong style={{ fontSize: 18, color: "#020202" }}>
                  {selectedLead.leadName}
                </Text>
              </Col>
              <Col span={12} className="text-right">
                {getStatusTag(selectedLead.status)}
              </Col>
            </Row>

            <Divider style={{ borderColor: "#F2EBF7" }} />

            {/* ── Lead Contact ── */}
            <Row gutter={[16, 16]}>
              <Col span={12}>
                <Text type="secondary" style={{ color: "#547593" }}>
                  <MailOutlined className="mr-2" /> Email
                </Text>
                <br />
                <Text strong style={{ color: "#020202" }}>{selectedLead.email || "N/A"}</Text>
              </Col>
              <Col span={12}>
                <Text type="secondary" style={{ color: "#547593" }}>
                  <PhoneOutlined className="mr-2" /> Phone
                </Text>
                <br />
                <Text strong style={{ color: "#020202" }}>{selectedLead.phone_number || selectedLead.phone || "N/A"}</Text>
              </Col>
            </Row>

            <Divider style={{ borderColor: "#F2EBF7" }} />

            {/* ── Agent Details (NAYA SECTION) ── */}
            <Title level={5} style={{ color: "#5C039B" }}>
              <TeamOutlined className="mr-2" /> Assigned Agent
            </Title>

            <div style={{ backgroundColor: "#F2EBF7", padding: 16, borderRadius: 8, marginTop: 12, marginBottom: 8 }}>
              <Row gutter={[16, 16]} align="middle">
                <Col span={2}>
                  <Avatar
                    icon={<UserOutlined />}
                    style={{ backgroundColor: "#03A4F4" }}
                    size={42}
                  />
                </Col>
                <Col span={22}>
                  <Row gutter={[16, 8]}>
                    <Col span={8}>
                      <Text type="secondary" style={{ color: "#547593" }}>Agent Name</Text>
                      <br />
                      <Text strong style={{ color: "#020202" }}>{selectedLead.agentName || "N/A"}</Text>
                    </Col>
                    <Col span={8}>
                      <Text type="secondary" style={{ color: "#547593" }}>
                        <MailOutlined className="mr-1" /> Email
                      </Text>
                      <br />
                      <Text strong style={{ color: "#020202" }}>{selectedLead.agentEmail || "N/A"}</Text>
                    </Col>
                    <Col span={8}>
                      <Text type="secondary" style={{ color: "#547593" }}>
                        <PhoneOutlined className="mr-1" /> Phone
                      </Text>
                      <br />
                      <Text strong style={{ color: "#020202" }}>{selectedLead.agentPhone || "N/A"}</Text>
                    </Col>
                  </Row>
                </Col>
              </Row>
            </div>

            <Divider style={{ borderColor: "#F2EBF7" }} />

            {/* ── Property & Preferences ── */}
            <Title level={5} style={{ color: "#5C039B" }}>
              <PropertySafetyOutlined className="mr-2" /> Property & Preferences
            </Title>

            <div style={{ backgroundColor: "#F2EBF7", padding: 16, borderRadius: 8, marginTop: 12 }}>
              <Row gutter={[16, 16]}>
                <Col span={12}>
                  <Text type="secondary" style={{ color: "#547593" }}>Property Type:</Text>
                  <br />
                  <Text strong style={{ color: "#020202" }}>{selectedLead.property_type || "N/A"}</Text>
                </Col>
                <Col span={12}>
                  <Text type="secondary" style={{ color: "#547593" }}>Bedrooms:</Text>
                  <br />
                  <Text strong style={{ color: "#020202" }}>{selectedLead.bedrooms ? `${selectedLead.bedrooms} BHK` : "N/A"}</Text>
                </Col>

                <Col span={12}>
                  <Text type="secondary" style={{ color: "#547593" }}>Budget:</Text>
                  <br />
                  <Text strong style={{ color: "#020202" }}>{selectedLead.budget ? `AED ${selectedLead.budget}` : "N/A"}</Text>
                </Col>
                <Col span={12}>
                  <Text type="secondary" style={{ color: "#547593" }}>Preferred Location:</Text>
                  <br />
                  <Text strong style={{ color: "#020202" }}>{selectedLead.preferred_location || "N/A"}</Text>
                </Col>

                {selectedLead.visit_date && (
                  <Col span={12}>
                    <Text type="secondary" style={{ color: "#547593" }}>Scheduled Visit:</Text>
                    <br />
                    <Text strong style={{ color: "#64EF0A" }}>
                      {selectedLead.visit_date}{selectedLead.visit_time && ` at ${selectedLead.visit_time}`}
                    </Text>
                  </Col>
                )}

                <Col span={12}>
                  <Text type="secondary" style={{ color: "#547593" }}>Source:</Text>
                  <br />
                  <Tag style={{ backgroundColor: "#5C039B", color: "#fff" }} className="mt-1">{selectedLead.source || "Direct"}</Tag>
                </Col>

                <Col span={12}>
                  <Text type="secondary" style={{ color: "#547593" }}>Added On:</Text>
                  <br />
                  <Text strong style={{ color: "#020202" }}>{new Date(selectedLead.createdAt).toLocaleString()}</Text>
                </Col>
              </Row>
            </div>

          </div>
        )}
      </Modal>

    </div>
  );
};

export default LeadManagement;